server {
    listen 8080 ssl;
    listen [::]:8080 ssl;
    http2 on;
    server_name oci.tianyue.ren;

    ssl_certificate /home/openresty/.acme.sh/oci.tianyue.ren_ecc/fullchain.cer;
    ssl_certificate_key /home/openresty/.acme.sh/oci.tianyue.ren_ecc/oci.tianyue.ren.key;

    server_tokens off;
    add_header Cache-Control "no-cache" always;
    add_header X-Content-Type-Options "nosniff" always;

    location = /hook {
	access_by_lua_block {
            local cmd = "sudo -u openresty /home/openresty/bin/hook.sh &"
            local status = os.execute(cmd)
	    ngx.log(ngx.NOTICE, "hook.sh executed as openresty")
	}
        content_by_lua_block {
	    ngx.header.content_type = "application/json"
            ngx.say('{"Status": "Successful"}')
	    ngx.exit(200)
        }
    }

    location = /hoom-view.html {
	root /home/openresty/html;
	default_type "text/html";
    }

    location = /hook-log {
        root /home/openresty/html;
	try_files /hook-view.html =404;
    }

    location = /hook-view {
	root /home/openresty/html;
	rewrite ^ /hook.log break;
	default_type "text/plain; charset=utf-8";
    }

    location / {
	return 404;
    }

    access_log /var/log/openresty/hook.access.log combined;
    error_log /var/log/openresty/hook.error.log notice;
}
